name: base
category: dev
channels:
- conda-forge
dependencies:
- git  # Also installed from Ubuntu, but this is newer.
- xonsh
- pre-commit
- ruff
- pytest
- dasel
- mamba
- pipx
- condax
- ipykernel  # Jupyter notebooks in VS Code
- nbformat  # Additional utilities for Jupyter notebooks (e.g. Plotly support)
- line_profiler
- cookiecutter
- cruft
- pandas
- numpy
- seaborn
- matplotlib
- scikit-learn
- biopython
- emboss
- jupyterlab

# # In case you want to install packages from PyPI which aren't on Conda-Forge,
# # uncomment this block and add them as follows:
# - pip:
#   - flake8-noqa  # Example
